name: Android CI Build - Rodyto Lens Pro

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Configurar SDK de Android
      uses: android-actions/setup-android@v3

    - name: Instalar NDK y CMake específicos
      run: |
        echo "y" | sdkmanager --install "ndk;25.1.8937393" "cmake;3.22.1"
        echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.1.8937393" >> $GITHUB_ENV

    - name: Generar Gradle Wrapper Estable
      # Forzamos la versión 8.7 que es extremadamente estable y compatible con Java 17
      run: gradle wrapper --gradle-version 8.7

    - name: Dar permisos de ejecución
      run: chmod +x gradlew

    - name: Sincronizar y Compilar APK (Debug)
      # Ahora usamos ./gradlew (el que acabamos de generar) en lugar del gradle del sistema
      run: ./gradlew assembleDebug --stacktrace

    - name: Subir APK generado
      uses: actions/upload-artifact@v4
      with:
        name: RodytoLensPro-Alpha
        path: app/build/outputs/apk/debug/app-debug.apk
